language: php

php:
  - 5.3.3

before_script:
  - composer selfupdate
  - composer install --dev

# lancement test phpunit
script: 
  - phpunit --coverage-clover coverage.clover

after_script: 
  # lancement test SensioLabs Insight
  - 'curl -X POST -H "Accept: application/vnd.com.sensiolabs.insight+xml" "https://56d75495-85ba-4894-9cd6-1033c25cc168:8bf2365488e3324ad8405b43b414c6571a608bf1ea10c3440e137c06a55c0792@insight.sensiolabs.com/api/projects/94ad6866-a596-4429-8bef-759b7933c7c2/analyses"'
  # lancement test scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    - benijaco@gmail.com