<?php

namespace Benijaco\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
   
    public function getArticlesAvecCommentaires()
    {
        $qb = $this->createQueryBuilder('a')
                   ->leftJoin('a.commentaires', 'c')
                   ->addSelect('c');

        return $qb->getQuery()
                  ->getResult();
    }
    
    
    public function getArticlesAvecCategories(array $nom_categories)
    {
        $qb = $this->createQueryBuilder('a')
                   ->leftJoin('a.categories', 'c')
                   ->where($qb->expr()->in('c.nom', $nom_categories));

        return $qb->getQuery()
                  ->getResult();
    }
}
