benijacoblog_accueil:
    pattern:   /
    defaults:  { _controller: BenijacoBlogBundle:Blog:index }
     
benijacoblog_voir:
    pattern:   /article/{id}
    defaults:  { _controller: BenijacoBlogBundle:Blog:voir }
     
benijacoblog_ajouter:
    pattern:   /ajouter
    defaults:  { _controller: BenijacoBlogBundle:Blog:ajouter }