parameters:
#    benijaco_blog.example.class: Benijaco\BlogBundle\Example

services:
#    benijaco_blog.example:
#        class: %benijaco_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    sdzblog.validator.antiflood:                             # Le nom du service
        class: Benijaco\BlogBundle\Validator\AntiFloodValidator   # La classe du service, ici notre validateur déjà créé
        arguments: [@request, @doctrine.orm.entity_manager]  # Les données qu'on injecte au service : la requête et l'EntityManager
        scope: request                                       # Comme on injecte la requête, on doit préciser ce scope
        tags:
            - { name: validator.constraint_validator, alias: benijacoblog_antiflood }  # C'est avec l'alias qu'on retrouvera le service